version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
    ports:
      - 5440:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 20000:8080

  rabbit:
    image: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1234
    volumes:
      - ./tmp/rabbit-data:/var/lib/rabbitmq
    ports:
      - 5680:5672
